[package]
name = "cs248-computer-graphics"
version = "0.1.0"
authors = ["Ivan Skorokhodov <iskorokhodov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
